JAVA_PKG_BASENAME=foundation.pEp.pitytest.examples
JAVA_PKG_BASEPATH=foundation/pEp/pitytest/examples
JAVA_CWD=../../../../../

JAVA_CLASSES_PITYTEST= \
 	../../TestSuite.class \
 	../../TestUnit.class \
 	../../TestContextInterface.class \
 	../../AbstractTestContext.class \
 	../../TestLogger.class \
 	../../utils/TestUtils.class \
 	../../utils/Pair.class \
 	../../TestState.class \
 	../../TestResult.class

PITYTEST_DIR=../../
