JAVA_PKG_BASENAME=foundation.pEp
JAVA_PKG_BASEPATH=foundation/pEp
CLASSPATH=.
JAVA=java -enableassertions
JAVA_CWD=../../../

JAVA_CLASSES_PITYTEST= \
 	TestSuite.class \
 	TestUnit.class \
 	TestContextInterface.class \
 	AbstractTestContext.class \
 	TestLogger.class \
 	utils/TestUtils.class \
 	utils/Pair.class \
 	TestState.class \
 	TestResult.class \
 	StopWatch.class

