JAVA_PKG_BASENAME=foundation.pEp
JAVA_PKG_BASEPATH=foundation/pEp
CLASSPATH=.
JAVAC_CMD=javac -encoding UTF-8
JAVA=java -enableassertions
JAVA_CWD=../../../


JAVA_CLASSES_PITYTEST= \
 	TestSuite.class \
 	TestUnit.class \
 	TestContextInterface.class \
 	AbstractTestContext.class \
 	TestLogger.class \
 	utils/TestUtils.class \
 	utils/Pair.class \
 	TestState.class \
 	StopWatch.class

