include:
  - '.gitlab-ci-files/common-prepare.yml'

stages:
  - build
  - packages


# Debian

debian10:build:
  extends: .make_in_docker
  stage: build
  variables:
    MAKE_TARGET: "build"
    CI_DISTRO_TARGET: "debian10"
    DEBIAN_FRONTEND: "noninteractive"
  rules:
    - if: '$CI_COMMIT_TAG  !~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

debian10:tagged-build:
  extends: .make_in_docker
  stage: build
  variables:
    MAKE_TARGET: "build"
    CI_DISTRO_TARGET: "debian10"
    DEBIAN_FRONTEND: "noninteractive"
    TAGGED_BUILD: "true"
  rules:
    - if: '$CI_COMMIT_TAG  =~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

debian10-java8:build:
  extends: .make_in_docker
  stage: build
  variables:
    MAKE_TARGET: "java8"
    CI_DISTRO_TARGET: "debian10"
    DEBIAN_FRONTEND: "noninteractive"
  rules:
    - if: '$CI_COMMIT_TAG  !~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

debian10-java8:tagged-build:
  extends: .make_in_docker
  stage: build
  variables:
    CI_DISTRO_TARGET: "debian10"
    MAKE_TARGET: "java8"
    DEBIAN_FRONTEND: "noninteractive"
    TAGGED_BUILD: "true"
  rules:
    - if: '$CI_COMMIT_TAG  =~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

# CentOS

centos8:build:
  extends: .make_in_docker
  stage: build
  variables:
    MAKE_TARGET: "build"
    CI_DISTRO_TARGET: "centos8"
  rules:
    - if: '$CI_COMMIT_TAG  !~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

centos8:tagged-build:
  extends: .make_in_docker
  stage: build
  variables:
    MAKE_TARGET: "build"
    CI_DISTRO_TARGET: "centos8"
    TAGGED_BUILD: "true"
  rules:
    - if: '$CI_COMMIT_TAG  =~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

centos8:rpm:
  extends: .make_in_docker
  stage: packages
  needs: ["centos8:build"]
  variables:
    MAKE_TARGET: "rpm"
    CI_DISTRO_TARGET: "centos8"
  rules:
    - if: '$CI_COMMIT_TAG  !~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'


centos8:rpm:tagged-build:
  extends: .upload_pkg
  stage: packages
  needs: ["centos8:tagged-build"]
  variables:
    MAKE_TARGET: "rpm"
    CI_DISTRO_TARGET: "centos8"
    TAGGED_BUILD: "true"
  rules:
    - if: '$CI_COMMIT_TAG  =~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'
