include:
  - '.gitlab-ci-files/common-prepare.yml'

stages:
  - build


# CentOS/RHEL

centos8:build:
  extends: .make_in_docker
  stage: build
  variables:
    CI_DISTRO_TARGET: "centos8"

centos8:tagged-build:
  extends: .make_in_docker
  stage: build
  variables:
    CI_DISTRO_TARGET: "centos8"
    TAGGED_BUILD: "true"
  rules:
    - if: $CI_COMMIT_TAG

# Debian

debian10:build:
  extends: .make_in_docker
  stage: build
  variables:
    CI_DISTRO_TARGET: "debian10"
    DEBIAN_FRONTEND: "noninteractive"

debian10:tagged-build:
  extends: .make_in_docker
  stage: build
  variables:
    CI_DISTRO_TARGET: "debian10"
    DEBIAN_FRONTEND: "noninteractive"
    TAGGED_BUILD: "true"
  rules:
    - if: $CI_COMMIT_TAG

