include:
  - '.gitlab-ci-files/common-prepare.yml'

stages:
  - build

# Debian

debian10:build:
  extends: .make_in_docker
  stage: build
  variables:
    CI_DISTRO_TARGET: "debian10"
    DEBIAN_FRONTEND: "noninteractive"
  rules:
    - if: '$CI_COMMIT_TAG  !~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

debian10:tagged-build:
  extends: .make_in_docker
  stage: build
  variables:
    CI_DISTRO_TARGET: "debian10"
    DEBIAN_FRONTEND: "noninteractive"
    TAGGED_BUILD: "true"
  rules:
    - if: '$CI_COMMIT_TAG  =~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

debian10-java8:build:
  extends: .make_in_docker
  stage: build
  variables:
    CI_DISTRO_TARGET: "debian10"
    MAKE_TARGET: "java8"
    DEBIAN_FRONTEND: "noninteractive"
  rules:
    - if: '$CI_COMMIT_TAG  !~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

debian10-java8:tagged-build:
  extends: .make_in_docker
  stage: build
  variables:
    CI_DISTRO_TARGET: "debian10"
    MAKE_TARGET: "java8"
    DEBIAN_FRONTEND: "noninteractive"
    TAGGED_BUILD: "true"
  rules:
    - if: '$CI_COMMIT_TAG  =~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'
