JAVA_PKG_BASENAME=foundation.pEp.jniadapter.test.utils.transport.fsmsgqueue.test
JAVA_PKG_BASEPATH=foundation/pEp/jniadapter/test/utils/transport/fsmsgqueue/test
JAVA_CWD=../../../../../../../../../
JAVA=java -enableassertions

JAVA_CLASSES_FSMSGQUEUE= \
 	../../FsMsgQueue.class

JAVA_CLASSES_PITYTEST= \
 	../../../../../pitytest/TestSuite.class \
 	../../../../../pitytest/TestUnit.class \
 	../../../../../pitytest/TestContextInterface.class \
 	../../../../../pitytest/AbstractTestContext.class \
 	../../../../../pitytest/TestLogger.class \
 	../../../../../pitytest/utils/TestUtils.class \
 	../../../../../pitytest/utils/Pair.class \
 	../../../../../pitytest/TestState.class \
 	../../../../../pitytest/TestResult.class

JAVA_CLASSES_TESTSCOMMON += $(JAVA_CLASSES_PITYTEST)