JAVA_PKG_BASENAME=foundation.pEp.jniadapter.test.utils.transport.fsmsgqueue.test
JAVA_PKG_BASEPATH=foundation/pEp/jniadapter/test/utils/transport/fsmsgqueue/test
JAVA_CWD=../../../../../../../../../
JAVA=java -enableassertions
JAVAC_CMD=javac -encoding UTF-8

JAVA_CLASSES_FSMSGQUEUE= \
 	../../FsMsgQueue.class

PITYTEST_DIR=../../../../../../../pitytest
