JAVA_PKG_BASENAME=foundation.pEp.jniadapter.test.utils.fsmsgqueue.test
JAVA_PKG_BASEPATH=foundation/pEp/jniadapter/test/utils/fsmsgqueue/test
JAVA_CWD=../../../../../../../../
JAVA=java -enableassertions

JAVA_CLASSES_FSMSGQUEUE= \
 	../../FsMsgQueue.class
