/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pEp_jniadapter_AndroidHelper */

#ifndef _Included_org_pEp_jniadapter_AndroidHelper
#define _Included_org_pEp_jniadapter_AndroidHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pEp_jniadapter_AndroidHelper
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_org_pEp_jniadapter_AndroidHelper_setenv
  (JNIEnv *, jclass, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
