JAVA_PKG_BASENAME=foundation.pEp.jniadapter.test.pitytest.examples
JAVA_PKG_BASEPATH=foundation/pEp/jniadapter/test/pitytest/examples
JAVA_CWD=../../../../../../../
JAVA=java -enableassertions

JAVA_CLASSES_PITYTEST= \
 	../../TestSuite.class \
 	../../TestUnit.class \
 	../../TestContextInterface.class \
 	../../AbstractTestContext.class \
 	../../TestLogger.class \
 	../../utils/TestUtils.class \
 	../../utils/Pair.class \
 	../../TestState.class \
 	../../TestResult.class

