JAVA_PKG_BASENAME=foundation.pEp.jniadapter.test
JAVA_PKG_BASEPATH=foundation/pEp/jniadapter/test
REPOROOT=../..
JAVA_CWD=../../../../../
JAVA_RESOURCES_DIR=../resources
JAVA_PEP_HOME_DIR=$(JAVA_RESOURCES_DIR)/pep-home
PEP_HOME_DIR=$(JAVA_CWD)$(JAVA_PEP_HOME_DIR)
CLASSPATH=.:$(REPOROOT)/src

JAVA=java -Xcheck:jni -cp $(CLASSPATH) -Djava.library.path=$(CLASSPATH)


$(info If on Mac, make sure to disable SIP, or copy the libpEpEngine.dylib into here)
ifdef ENGINE_LIB_PATH
	ifeq ($(BUILD_FOR),Linux)
	  ifndef LD_LIBRARY_PATH
	    export LD_LIBRARY_PATH=$(ENGINE_LIB_PATH)
	  endif
	else ifeq ($(BUILD_FOR),Darwin)
	  ifndef DYLD_LIBRARY_PATH
	    export DYLD_LIBRARY_PATH=$(ENGINE_LIB_PATH)
	  endif
	endif
endif

