JAVA_PKG_BASENAME=foundation.pEp.jniadapter.test
JAVA_PKG_BASEPATH=foundation/pEp/jniadapter/test
REPOROOT=../..
DIST_DIR=$(REPOROOT)/dist
JAVA_CWD=../../../../../
JAVA_RESOURCES_DIR=../resources

JAVA_PEP_HOME_DIR_ALICE=$(JAVA_RESOURCES_DIR)/per-user-dirs/alice
JAVA_PEP_HOME_DIR_BOB=$(JAVA_RESOURCES_DIR)/per-user-dirs/bob
JAVA_PEP_HOME_DIR_CAROL=$(JAVA_RESOURCES_DIR)/per-user-dirs/carol
JAVA_PEP_HOME_DIR=$(JAVA_PEP_HOME_DIR_ALICE)

PEP_HOME_DIR_ALICE=$(JAVA_CWD)$(JAVA_PEP_HOME_DIR_ALICE)
PEP_HOME_DIR_BOB=$(JAVA_CWD)$(JAVA_PEP_HOME_DIR_BOB)
PEP_HOME_DIR_CAROL=$(JAVA_CWD)$(JAVA_PEP_HOME_DIR_CAROL)
PEP_HOME_DIR=$(PEP_HOME_DIR_ALICE)

CLASSPATH=.:$(DIST_DIR)/pEp.jar
LD_LIB_PATH=.:$(DIST_DIR)

# Java cmd-line options
JAVA_OPT_ASSERTIONS=-enableassertions
JAVA_OPT_XCHECK=-Xcheck:jni
# JAVA_OPT_REMOTE_DEBUGGER=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=localhost:5005 -cp $(CLASSPATH) -Djava.library.path=$(LD_LIB_PATH)
JAVA_OPT_CLASSPATH=-cp $(CLASSPATH) -Djava.library.path=$(LD_LIB_PATH)
JAVA_OPT_LIBARY_PATH=-Djava.library.path=$(LD_LIB_PATH)

JAVA_OPTS=$(JAVA_OPT_ASSERTIONS) $(JAVA_OPT_XCHECK) $(JAVA_OPT_REMOTE_DEBUGGER) $(JAVA_OPT_CLASSPATH) $(JAVA_OPT_LIBARY_PATH)
JAVA=java $(JAVA_OPTS)

UTIL_SOURCES=$(wildcard ../utils/*.java)
UTIL_CLASSES=$(subst .java,.class,$(UTIL_SOURCES))
JAVA_CLASSES+=$(UTIL_CLASSES)

PITYTEST_DIR=../../../pitytest

ifdef ENGINE_LIB_PATH
	ifeq ($(PLATFORM),linux)
	  ifndef LD_LIBRARY_PATH
	    export LD_LIBRARY_PATH=$(ENGINE_LIB_PATH)
	  endif
	else ifeq ($(PLATFORM),darwin)
	  ifndef DYLD_LIBRARY_PATH
	    export DYLD_LIBRARY_PATH=$(ENGINE_LIB_PATH)
	  endif
	endif
endif

