JAVA_PKG_BASENAME=foundation.pEp.jniadapter.test.utils.transport.fsmqmanager.test
JAVA_PKG_BASEPATH=foundation/pEp/jniadapter/test/utils/transport/fsmqmanager/test
JAVA_CWD=../../../../../../../../../
JAVA=java -enableassertions

JAVA_CLASSES_FSMSGQUEUE= \
 	../../FsMQManager.class \
 	../../FsMQIdentities.class \
 	../../FsMQIdentity.class \
 	../../FsMQMessage.class \
 	../../UnknownIdentityException.class \
 	../../../fsmsgqueue/FsMsgQueue.class

JAVA_CLASSES_TESTSCOMMON= \
	../utils/FsMQManagerTestUtils.class \
	../ctx/FsMQManagerBaseTestContext.class
