JAVA_PKG_BASENAME=foundation.pEp.jniadapter.test.utils.transport.fsmqmanager.test
JAVA_PKG_BASEPATH=foundation/pEp/jniadapter/test/utils/transport/fsmqmanager/test
JAVA_CWD=../../../../../../../../../
JAVA=java -enableassertions

JAVA_CLASSES_FSMSGQUEUE= \
 	../../FsMQManager.class \
 	../../FsMQIdentity.class \
 	../../UnknownIdentityException.class \
 	../../../fsmsgqueue/FsMsgQueue.class
