JAVA_PKG_BASENAME=foundation.pEp.jniadapter.test.framework.examples
JAVA_PKG_BASEPATH=foundation/pEp/jniadapter/test/framework/examples
JAVA_CWD=../../../../../../../
JAVA=java

JAVA_CLASSES_FRAMEWORK= \
 	../../TestUnit.class \
 	../../AbstractTestContext.class \
 	../../TestLogger.class \
 	../../TestUtils.class
